import React, { useEffect, useState } from "react";
import clsx from "clsx";
import { Plot, Point } from "./components/Plot/Plot";
import { CustomTable } from "./components/Table/Table";
import { Theme } from "@mui/material/styles";
import { makeStyles } from "./makeStyles";


import {
  CssBaseline,
  Switch,
  Drawer,
  Box,
  AppBar,
  Toolbar,
  List,
  Avatar,
  Typography,
  Divider,
  IconButton,
  Badge,
  Container,
  Grid,
  Paper,
  Link,
  ListItemIcon,
  ListItem,
  ListItemText,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu";
import {
  ChevronLeft as ChevronLeftIcon,
  Notifications as NotificationsIcon,
  Dashboard as DashboardIcon,
  Star
} from "@mui/icons-material";
import { ThemeProvider, StyledEngineProvider, createTheme } from '@mui/system';

const url = 'ws://127.0.0.1:8080/ws'
const ws = new WebSocket(url);

// The point of x should be the time
// Generated by Date.now()
type MQTTTopic = "temperature" | "humidity"
interface MQTTMsg {
  topic: MQTTTopic;
  payload: string;
}


const drawerWidth = 240;
// FIXME: CSS Priority
// Is overridden by Mui** classes
// @ts-ignore I don't know how to fix this, but it works
const useStyles = makeStyles()((theme: Theme) => ({
  "root": {
    display: "flex"
  },
  "toolbar": {
    paddingRight: 24 // keep right padding when drawer closed
  },
  "toolbarIcon": {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: "0 8px",
    ...theme.mixins.toolbar
  },
  "appBar": {
    zIndex: theme.zIndex.drawer + 1,
    transition: theme.transitions.create(["width", "margin"], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.leavingScreen
    })
  },
  "appBarShift": {
    marginLeft: drawerWidth,
    width: `calc(100% - ${drawerWidth}px)`,
    transition: theme.transitions.create(["width", "margin"], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen
    })
  },
  "menuButton": {
    marginRight: 36
  },
  "menuButtonHidden": {
    display: "none"
  },
  "title": {
    flexGrow: 1
  },
  "drawerPaper": {
    position: "relative",
    whiteSpace: "nowrap",
    width: drawerWidth,
    transition: theme.transitions.create("width", {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen
    })
  },
  "drawerPaperClose": {
    overflowX: "hidden",
    transition: theme.transitions.create("width", {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.leavingScreen
    }),
    width: theme.spacing(7),
    [theme.breakpoints.up("sm")]: {
      width: theme.spacing(9)
    }
  },
  "appBarSpacer": theme.mixins.toolbar,
  "content": {
    flexGrow: 1,
    height: "100vh",
    overflow: "auto"
  },
  "container": {
    paddingTop: theme.spacing(4),
    paddingBottom: theme.spacing(4)
  },
  "paper": {
    padding: theme.spacing(2),
    display: "flex",
    overflow: "auto",
    flexDirection: "column"
  },
  "fixedHeight": {
    height: 240
  }
}));

export default function Dashboard() {
  const [open, setOpen] = useState(false);
  const [darkState, setDarkState] = useState(false);
  const [data, setData] = useState<Point[]>([{ x: Date.now(), y: 0 }]);
  const {classes, cx}  = useStyles();
  let tempData: Point[] = [];
  const PLOT_LENGTH = 10;

  useEffect(() => {
    ws.onmessage = (event) => {
      const msg = event.data
      try {
        const parsed: MQTTMsg = JSON.parse(msg)
        console.log(parsed)
        if (parsed.topic === "temperature") {
          const newPt = { x: Date.now(), y: parseFloat(parsed.payload) }
          // https://stackoverflow.com/questions/55565444/how-to-register-event-with-useeffect-hooks
          // I don't know why but the last data must be used
          setData((d) => {
            if (d.length > PLOT_LENGTH) {
              const temp = d.slice((-PLOT_LENGTH), -1)
              // for some reason slice is not including the last element
              temp.push(d.slice(-1)[0])
              // console.log([...temp, newPt])
              return [...temp, newPt]
            } else {
              tempData.push(newPt)
              return [...tempData]
            }
          })
          // console.log(tempData)
        }
      } catch (e) {
        console.error(e)
      }
    }
    return () => {
      ws.onmessage = null
    }
  }, []);


  const handleThemeChange = () => {
    setDarkState(!darkState);
  };

  const handleDrawerOpen = () => {
    setOpen(true);
  };
  const handleDrawerClose = () => {
    setOpen(false);
  };

  // @ts-ignore
  function createData(name, calories, fat, carbs, protein) {
    return { name, calories, fat, carbs, protein };
  }

  const paperClass = clsx(classes.paper);
  return (
    <div id="Dashboard" className={classes.root}>
      <AppBar
        position="absolute"
        className={clsx(classes.appBar, open && classes.appBarShift)}
      >
        <Toolbar className={classes.toolbar}>
          <IconButton
            edge="start"
            color="inherit"
            aria-label="open drawer"
            onClick={handleDrawerOpen}
            className={clsx(
              classes.menuButton,
              open && classes.menuButtonHidden
            )}
            size="large">
            <MenuIcon />
          </IconButton>
          <Typography
            component="h1"
            variant="h6"
            color="inherit"
            noWrap
            className={classes.title}
          >
            IOT Dashboard
          </Typography>
          <Switch checked={darkState} onChange={handleThemeChange} />
        </Toolbar>
      </AppBar>
      <Drawer
        variant="permanent"
        classes={{
          paper: clsx(classes.drawerPaper, !open && classes.drawerPaperClose)
        }}
        open={open}
      >
        <div className={classes.toolbarIcon}>
          <IconButton onClick={handleDrawerClose} size="large">
            <ChevronLeftIcon />
          </IconButton>
        </div>
        <Divider />
        <List>{
          <ListItem button>
            <ListItemIcon>
              <DashboardIcon />
            </ListItemIcon>
            <ListItemText primary="Dashboard" />
          </ListItem>
        }</List>
        <Divider />
        <List>{
          <ListItem button>
            <ListItemIcon>
              <Star />
            </ListItemIcon>
            <ListItemText primary="Star" />
          </ListItem>
        }</List>
      </Drawer>

      <main className={classes.content}>
        <div className={classes.appBarSpacer} />
        <Container maxWidth="lg" className={classes.container}>
          <Grid container spacing={3}>
            {/* Chart */}
            <Grid item xs={12} md={8} lg={9}>
              <Paper className={paperClass}>
                <Plot data={data} />
              </Paper>
            </Grid>
            {/* Recent Deposits */}
            <Grid item xs={12} md={4} lg={3}>
              <Paper className={paperClass}>
                <CustomTable rows={data} />
              </Paper>
            </Grid>
            {/* Chart */}
            <Grid item xs={12} md={8} lg={9}>
              <Paper className={paperClass}>
                <Plot data={data} />
              </Paper>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  );
}